server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**

        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/events/**,/users/*/events/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: location-service-route
          uri: lb://location-service
          predicates:
            - Path=/admin/locations/**