server:
  port: 0
spring:
  application:
    name: location-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_main_db
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          event-service:
            connect-timeout: 5000   # 5 секунд на установление соединения
            read-timeout: 20000     # 10 секунд на ожидание ответа
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3               # количество попыток (включая первый вызов)
        wait-duration: 1s             # пауза между попытками
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 50
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      event-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      event-service:
        base-config: default