CREATE TABLE IF NOT EXISTS admin_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    radius FLOAT NOT NULL CHECK (radius > 0),
    CONSTRAINT uq_admin_location_name UNIQUE (name)
);